#!/usr/bin/env bash
source $(dirname $0)/../../config
source $(dirname $0)/../../lib/redis

REDIS_KEY="${namespace}.disk_used"
REDIS_EXPIRE=5

_usage() {
  echo "$0 [get|set]"
}

function _disk_used() {
  df | awk '/\/$/ { print int($5) }'
}

redis_get || redis_set $(_disk_used)
