#!/usr/bin/env bash
source $(dirname $0)/../../config
source $(dirname $0)/../../lib/redis

REDIS_KEY="${namespace}.cpu_used"
REDIS_EXPIRE=5

_usage() {
  echo "$0 [get|set]"
}

_cpu_used() {
  samples_to_take=2
  top -bn${samples_to_take} \
    | awk '
            /\%Cpu\(s\):/ {
                            idle=$8;
                            stolen=$16;
                          }
            END           {
                            capacity = 100 - stolen
                            used = capacity - idle
                            print int(used)
                          }
          '
}

redis_get || redis_set $(_cpu_used)
