#!/usr/bin/env bash
free -m \
  | awk '
    /^Mem/  {
                total = $2;
                available = $7;
            }
    END     {
                unavalable = total - available
                print int(100 / ( total / unavalable ))
            }
  '
