#!/usr/bin/env bash
samples_to_take=${1:-2}
top -bn${samples_to_take} \
  | awk '
          /\%Cpu\(s\):/ {
                          idle+=$8;
                          stolen+=$16;
                          n+=1;
                        }
          END           {
                          idle = idle / n
                          stolen = stolen / n
                          capacity = 100 - stolen
                          used = capacity - idle
                          print used
                        }
        '
